### ISSUE TITLE
A good symbol website recommendation

### ISSUE THREAD

**Issue by hongjiang11** [nappa85/symbols#2]
English https://www.getsymbol.net/
Spanish https://www.getsymbol.net/es
Japanese https://www.getsymbol.net/ja

![2](https://github.com/user-attachments/assets/ba8024ae-2b5e-48f6-bcb2-0867f4ae29ee)

**Comment by nappa85** [comment]
Sorry, I'm not getting the point of this issue. Can you please explain?

**Comment by zoten** [comment]
It's clearly a high priority feature you should already have in your backlog, please implement
